all:
  javascripts: [pos]
ajaxSuccess:
  has_layout: false
  http_metas:
    content-type: application/json
salesEvolutionJson:
  has_layout: false
  http_metas:
    content-type: application/json
stateJson:
  has_layout: false
  http_metas:
    content-type: application/json
