default:
  stylesheets: [contact-card-form]
  javascripts: []
indexSuccess:
  javascripts: [rp-member-card-seat, rp-member-card-batch]
csvSuccess:
  has_layout: false
  http_metas:
    content-type: text/comma-separated-values
    content-disposition: attachment; filename="membercards.csv"
setSeatSuccess:
  has_layout: false
  http_metas:
    content-type: application/json
cardPrint:
  javascripts: [-*]
  stylesheets: [-*]
