# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/12-Filters

rendering: ~
security:  ~

remember_me:
  class: sfGuardRememberMeFilter

  <?php
    $modules = array();
    if ( is_readable($file = __DIR__.'/extra-modules.php') )
      $modules = require($file);
    if ( !is_array($modules) )
      $modules = array();
    if ( !is_array($modules['filters']) )
      $modules['filters'] = array();
    $filters = $modules['filters'];
    echo PHP_EOL;
  ?>

<?php foreach ( $filters as $filter => $option ): ?>
<?php echo "$filter: $option".PHP_EOL ?>
<?php endforeach; echo PHP_EOL; ?>

# insert your own filters here

exceptionCatcherFilter: ~

cache:     ~
execution: ~
