<?php

/**
 * PluginCheckpointTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCheckpointTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCheckpointTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCheckpoint');
    }
    
    public function getFromManifestations($mids, $type = 'entrance')
    {
      return Doctrine_Query::create()
        ->select('cp.id')
        ->from('Checkpoint cp')
        ->innerJoin('cp.Event e')
        ->innerJoin('e.Manifestations m')
        ->andWhere('cp.type = ?', $type)
        ->andWhereIn('m.id', $mids);
    }
    
    public function getFromManifestation($manifestation_id, $type = 'entrance')
    {
      return $this->getFromManifestations($manifestation_id, $type)
        ->fetchOne();
    }
    
}