generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PaymentMethod
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          payment_method
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        member_card_linked: { label: "Linked w/ MC?", credentials: [tck-admin-member-cards] }
        ept: { label: "EPT" }
        Picture: { label: Pictogram, help: 32 x 32px }
        list_picture: { label: Pictogram }
      list:
        display: [name, account, display, member_card_linked, ept, _list_picture, rank]
      filter:  ~
      show:
        display:
          General: [name, account, display, member_card_linked, ept, Picture, _show_picture, _form_picture_del]
          Users: [_show_users_list]
      form:
        fields:
          ept: { label: "Electronic payment terminal" }
          users_list: { label: "Excluded users" }
        display:
          General: [name, account, display, member_card_linked, ept, Picture, _show_picture, _form_picture_del]
          Users: [users_list] 
      edit:    ~
      new:     ~
