default:
  javascripts: [jquery?<?php echo date('Ymd') ?>, geo-street-base?<?php echo date('Ymd') ?>]
indexSuccess:
  #stylesheets: [/sfDoctrinePlugin/css/global.css, /sfDoctrinePlugin/css/default.css, /sfAdminThemejRollerPlugin/css/jroller.css, /sfAdminThemejRollerPlugin/css/jquery/redmond/jquery-ui.custom.css]
  javascripts: [helper, photobooth]
