generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Transaction
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          transaction_debts
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        all: { label: "Even closed transactions ?" }
        date: { label: "Created at", type: date }
        User: { label: "Last user" }
      list:
        title: Debts
        display: [_id, _invoice_id, _contact, _professional, _debt, _created_at, _updated_at, _user]
        actions:
          _extract:
            action: 'index#csv'
            ui-icon: document
        object_actions:
          _show: ~
        batch_actions: []
        table_method: findDebts #retrieveDebtsList
        table_count_method: findDebtsCount
        sort: [updated_at, desc]
        max_per_page: 500
        pager_class: liCustomPager
      filter:
        display: [created_by, date, all]
        class: DebtsFormFilter
      form:    ~
      edit:    ~
      new:     ~
