# config/services.yml
dev:
  parameters:

all:
  parameters:

  services:
    dummy:
      abstract: true
    manifestations_service:
      class: ManifestationsService
    app_country_service:
      class: CountryService
    pub_service:
      class: PubService
    password_plain_text_service:
      class: PasswordPlainTextService
    password_md5_service:
      class: PasswordMD5Service

