# config/services.yml
dev:
  parameters:

all:
  parameters:
    
  services:
    dummy:
      abstract: true
    manifestations_service:
      class: ManifestationsService
    app_country_service:
      class: CountryService
    pub_service:
      class: PubService

