generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ManifestationPicture
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          manifestation_picture
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [id, manifestation_id, picture_id]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
